---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/nfd.k8s-sigs.io/nodefeaturerule_v1alpha1.json
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: nabucasa-skyconnect-device
spec:
  rules:
    - name: nabucasa-skyconnect
      labels:
        nabucasa.feature.node.kubernetes.io/skyconnect: "true"
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            device: { op: In, value: ["ea60"] }
            vendor: { op: In, value: ["10c4"] }
