---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: rook-ceph
      version: v1.18.3
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: snapshot-controller
  values:
    csi:
      enableCephfsDriver: false
      enableLiveness: true
      serviceMonitor:
        enabled: true
    csiRBDProvisionerResource: |
      - name : csi-provisioner
        resource:
          requests:
            memory: 128Mi
            cpu: 25m
          limits:
            memory: 256Mi
      - name : csi-resizer
        resource:
          requests:
            memory: 128Mi
            cpu: 25m
          limits:
            memory: 256Mi
      - name : csi-attacher
        resource:
          requests:
            memory: 128Mi
            cpu: 25m
          limits:
            memory: 256Mi
      - name : csi-snapshotter
        resource:
          requests:
            memory: 128Mi
            cpu: 25m
          limits:
            memory: 256Mi
      - name : csi-rbdplugin
        resource:
          requests:
            memory: 512Mi
            cpu: 50m
          limits:
            memory: 1Gi
      - name : csi-omap-generator
        resource:
          requests:
            memory: 512Mi
            cpu: 50m
          limits:
            memory: 1Gi
      - name : liveness-prometheus
        resource:
          requests:
            memory: 128Mi
            cpu: 25m
          limits:
            memory: 256Mi

    csiCephFSProvisionerResource: |
      - name : csi-provisioner
        resource:
          requests:
            memory: 128Mi
            cpu: 25m
          limits:
            memory: 256Mi
      - name : csi-resizer
        resource:
          requests:
            memory: 128Mi
            cpu: 25m
          limits:
            memory: 256Mi
      - name : csi-attacher
        resource:
          requests:
            memory: 128Mi
            cpu: 25m
          limits:
            memory: 256Mi
      - name : csi-snapshotter
        resource:
          requests:
            memory: 128Mi
            cpu: 25m
          limits:
            memory: 256Mi
      - name : csi-cephfsplugin
        resource:
          requests:
            memory: 512Mi
            cpu: 50m
          limits:
            memory: 1Gi
      - name : liveness-prometheus
        resource:
          requests:
            memory: 128Mi
            cpu: 25m
          limits:
            memory: 256Mi
    monitoring:
      enabled: true
    resources:
      requests:
        cpu: 50m
        memory: 512Mi
      limits:
        memory: 512Mi

