---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-generic
allowVolumeExpansion: true
parameters:
  fstype: zfs
  poolname: zroot/srv/generic
  recordsize: 128k
  compresion: lz4
  dedup: off
  thinprovision: yes
  shared: yes
provisioner: zfs.csi.openebs.io
volumeBindingMode: WaitForFirstConsumer
