---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-database
allowVolumeExpansion: true
parameters:
  fstype: zfs
  poolname: zroot/srv/database
  recordsize: 16k
  compresion: lz4
  dedup: off
  thinprovision: yes
  shared: no
provisioner: zfs.csi.openebs.io
volumeBindingMode: WaitForFirstConsumer
