---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app k8s-gateway
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      k8s-gateway:
        type: deployment
        replicas: 3
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/k8s-gateway/k8s_gateway
              tag: 1.5.2
            args: ["-conf", "/etc/coredns/Corefile"]
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 8080
                  initialDelaySeconds: 60
                  timeoutSeconds: 5
                  successThreshold: 1
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ready
                    port: 8181
                  initialDelaySeconds: 10
                  timeoutSeconds: 5
                  successThreshold: 1
                  failureThreshold: 5
    configMaps:
      k8s-gateway:
        data:
          Corefile: |
            .:1053 {
              k8s_gateway rx.cz {
                apex k8s-gateway.network
                resources Ingress
                ttl 1
              }
              errors
              health {
                lameduck 5s
              }
              ready
              prometheus 0.0.0.0:9153
              forward . /etc/resolv.conf
              cache 30
              loop
              reload
              loadbalance
            }
            storage.rx.cz:1053 {
              errors
              forward . 192.168.1.19
              cache 30
            }
    defaultPodOptions:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: *app
                topologyKey: kubernetes.io/hostname
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
    persistence:
      config:
        type: configMap
        name: k8s-gateway
        globalMounts:
          - path: /etc/coredns/Corefile
            subPath: Corefile
            readOnly: true
    service:
      app:
        controller: k8s-gateway
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          lbipam.cilium.io/ips: "192.168.1.49"
        ports:
          dns-udp:
            port: 53
            protocol: UDP
            targetPort: 1053
            nodePort: 30584
    serviceAccount:
      create: true
