---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: volsync-secret-store
spec:
  provider:
    kubernetes:
      remoteNamespace: storage
      auth:
        serviceAccount:
          name: volsync-secret-manager
          namespace: storage
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: storage
          key: ca.crt
