---
apiVersion: postgresql.cnpg.io/v1
kind: ImageCatalog
metadata:
  name: timescaledb
spec:
  images:
    - major: 16
      # renovate: datasource=docker
      image: ghcr.io/imusmanmalik/timescaledb-postgis:16-3.4-68
