---
apiVersion: postgresql.cnpg.io/v1
kind: ImageCatalog
metadata:
  name: timescaledb
spec:
  images:
    - major: 16
      # renovate: datasource=docker
      image: ghcr.io/imusmanmalik/timescaledb-postgis:17-3.5-17
