---
apiVersion: postgresql.cnpg.io/v1
kind: ImageCatalog
metadata:
  name: timescaledb
spec:
  images:
    - major: 16
      # renovate: datasource=docker
      image: docker.io/timescale/timescaledb-ha:pg16.3-ts2.15.0
