---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cluster16.yaml
  - ./postgres17.yaml
  - ./imagecatalog.yaml
  - ./prometheusrule.yaml
  - ./secret.sops.yaml
  - ./scheduledbackup.yaml
