---
apiVersion: v1
kind: ConfigMap
metadata:
  name: generic-device-plugin-config
data:
  config.yaml: |
    devices:
      - name: nabucasa-skyconnect
        groups:
          - paths:
              - path: /dev/serial/by-id/usb-Nabu_Casa_SkyConnect*
                mountPath: /dev/ttyUSB0
