---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app generic-device-plugin
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    defaultPodOptions:
      annotations:
        reloader.stakater.com/auto: "true"
      priorityClassName: system-node-critical
      tolerations:
        - operator: "Exists"
          effect: "NoExecute"
        - operator: "Exists"
          effect: "NoSchedule"
    controllers:
      generic-device-plugin:
        type: daemonset
        containers:
          app:
            image:
              repository: ghcr.io/squat/generic-device-plugin
              tag: latest
            args:
              - --config=/config/config.yaml
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup: *probes
            resources:
              requests:
                cpu: "5m"
              limits:
                memory: "64Mi"
            securityContext:
              privileged: true
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
    serviceAccount:
      create: true
      name: *app
    persistence:
      config:
        type: configMap
        name: generic-device-plugin-config
        globalMounts:
          - path: /config/config.yaml
            subPath: config.yaml
      device-plugins:
        type: hostPath
        hostPath: /var/lib/kubelet/device-plugins
        globalMounts:
          - path: /var/lib/kubelet/device-plugins
      dev:
        type: hostPath
        hostPath: /dev
        globalMounts:
          - path: /dev
