---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: redis-secret-store
spec:
  provider:
    kubernetes:
      remoteNamespace: database
      auth:
        serviceAccount:
          name: redis-secret-manager
          namespace: database
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: security
          key: ca.crt
