---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: postgres-secrets-store
spec:
  provider:
    kubernetes:
      remoteNamespace: storage
      auth:
        serviceAccount:
          name: postgres-secrets-manager
          namespace: security
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: security
          key: ca.crt
