---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ebusd-emqx-init
spec:
  target:
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        INIT_EMQX_API_HOST: "{{ .emqx_api_host }}"
        INIT_EMQX_API_PORT: "{{ .emqx_api_port }}"
        INIT_EMQX_ACCESS_KEY: "{{ .emqx_username }}"
        INIT_EMQX_SECRET_KEY: "{{ .emqx_password }}"
        INIT_EMQX_USER: "{{ .ebusd_username }}"
        INIT_EMQX_PASS: "{{ .ebusd_password }}"
        INIT_EMQX_TOPIC: "ebusd/#"
        INIT_EMQX_TOPIC_ACLS: >-
          {{ .ebusd_username }}:homeassistant/#:all:allow
          {{ .hass_username }}:ebusd/#:all:allow
  dataFrom:
    - extract:
        key: emqx-secret
      rewrite:
        - regexp:
            source: "^(.*)$"
            target: "emqx_$1"
      sourceRef:
        storeRef:
          name: emqx-secret-store
          kind: ClusterSecretStore
    - extract:
        key: ebusd-config-secret
      rewrite:
        - regexp:
            source: "^(.*)$"
            target: "ebusd_$1"
      sourceRef:
        storeRef:
          name: home-automation-secret-store
          kind: SecretStore
    - extract:
        key: home-assistant-emqx-secret
      rewrite:
        - regexp:
            source: "^(.*)$"
            target: "hass_$1"
      sourceRef:
        storeRef:
          name: home-automation-secret-store
          kind: SecretStore

