---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ebusd-secret
spec:
  target:
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # https://github.com/john30/ebusd/wiki/2.-Run
        # Device Options
        EBUSD_DEVICE: "{{ .ebusd_device }}"
        # MQTT Options
        EBUSD_MQTTHOST: "{{ .emqx_host }}"
        EBUSD_MQTTPORT: "{{ .emqx_port }}"
        EBUSD_MQTTUSER: "{{ .ebusd_username }}"
        EBUSD_MQTTPASS: "{{ .ebusd_password }}"
        # https://github.com/prehor/container-images/blob/main/apps/alpine-toolbox/entrypoint.sh
        GITCONFIG_USER_MAIL: "{{ .ebusd_github_user_mail}}"
        GITCONFIG_USER_NAME: "{{ .ebusd_github_user_name}}"
  dataFrom:
    - extract:
        key: ebusd-config-secret
      rewrite:
        - regexp:
            source: "^(.*)$"
            target: "ebusd_$1"
      sourceRef:
        storeRef:
          name: home-automation-secret-store
          kind: SecretStore
    - extract:
        key: emqx-secret
      rewrite:
        - regexp:
            source: "^(.*)$"
            target: "emqx_$1"
      sourceRef:
        storeRef:
          name: emqx-secret-store
          kind: ClusterSecretStore
