---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mqtt-secret
spec:
  dataFrom:
    - extract:
        key: mqtt-secret
      sourceRef:
        storeRef:
          name: mqtt-secret-store
          kind: ClusterSecretStore
