---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:

  force-reset:
    desc: Reset repo back to HEAD
    prompt: Reset repo back to HEAD... continue?
    cmds:
      - git reset --hard HEAD
      - git clean -f -d
      - git pull origin main
