apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:MxokyoY0S+AzDlPr4fmOV4VAxPCAhEmUZeQcW7RYj8V3UPlvbDf9Aw==,iv:11OjiqdaEk3Fi7EMOiKQLVN1HZjwQVz5a/OsawFbGT0=,tag:Hx7nZnGsFfwU1zU64VW4Ng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ve9kzacrwq7l9l0emvs326uk6t576d75r596e083r2tq6xu28qcsacy3s7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVUJrTTgyWWorV3loaHFD
            eTROZWdvcW41V3BCMkxNMEI0Slh1MEZEbWlvCjJqNmpaeXlaSE1sRWU2cGYrSnJ5
            em01R0FER2Vvc1dUblVjaXN0ZkJyYlkKLS0tIDU5Q0E4dWlUTnhKaTNNTnlGNEdt
            S1h1OEZxQ2ExV2dCQkZMbitDeTk0TzgK8c92z38xParQc9t4KVOSg1VfxeLVbfpt
            J0PJUarEyKFseUkwPk2NptHIM3F9dsbjJZEneJR2bOlxQAIhkRnh4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-21T17:52:58Z"
    mac: ENC[AES256_GCM,data:5M6VG+IBG9wiLEkmYhh0hMckE6lnUIJ3nSOoGzHu/snh+J5WKBekk7sFVoYY9cGhJwvyfuvA5J4dRzqEcZMxUGUVtciaDbHJ3Tk3niTjxaPqF3wcBCP9OK7v4Cm9kG4/4xi6jhbFjjSd8vHDilYOiXt5/6VQR9+uMsCKOaJNApU=,iv:eSueh85vuzfOh5hzkM7t0klDdqCKRkA4+V5wlAf6JXk=,tag:G7XAyIAFGKtx2sAxjivh/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
