---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app k8tz
  namespace: flux-system
spec:
  targetNamespace: kube-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cert-manager
  path: "./kubernetes/storage/apps/kube-system/k8tz/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
