apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_CLUSTER_NAME: ENC[AES256_GCM,data:3i/FUVaesvE=,iv:1q3r8FC/oeCX46hi9ROyrGVhUkwk81c1tQZQHmVXd+k=,tag:ctkNp30RUQmh+HG2w169iQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:0r9nF8Y=,iv:pTfIeRsxhWcJczBoWaLud8gIfxhlNZ/S7pfUBjct99M=,tag:pcjJXMulP5A3p/TOJK6lxQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:ocMoiAA04XI=,iv:Oqn7NoiaEzjwkRiWrFTptYxMIty2a6ZEi+nf7YordYE=,tag:QDqmOHhV2ZPOlG4+icRi4g==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:mX8r6K+3U7TU5bAw9HccDff6dibFaYfRePLab+mKcqLtRB8k,iv:wJUyMBIzv8qCAcRxWPFL8sEwuuaz9UKTHB/C216Zn2I=,tag:xlGVwhit/wgEwz3Dl+jWcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ve9kzacrwq7l9l0emvs326uk6t576d75r596e083r2tq6xu28qcsacy3s7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRDE0Uk5KaW5uRkNHaGpv
            VkgyV0N2RDNZS2Q4bXd2TVMxZWw4VStRc1hrCm5hNnA0ZEZTV2QyeEx1Zm5IbmZy
            am9TTk92V2RMWnlHcFZpZVcyb3FQRDQKLS0tIFQ3aVBhajVlZDJSWEtCcXhzc2Q3
            ME5zYlpMbVk3NHljVEdJNk1ocG91c28KNfYzJ15YFgpNvmM4mWC7FD4jTu/IwnHx
            SWN3WbZK2qc4oTrNBKTA8DQ+7MF4VbbBmq7FXVNYGVns9xDrgVO9DQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-21T17:52:58Z"
    mac: ENC[AES256_GCM,data:5EFSRRPIGzpll93vlGVBqHAEPm+vaUJI/re3l2IhrTqMUzX1BjcbkcdDSjEG2rdL06YLcFsUBhVBvBATuNThBRaRKO6YRpKyug5FaII/wbQqnqAPDD0xncLHaq0Bme34iIQ6jdbOisvuaOVBQYXZAyJUIy9RC8IL5cEdP79xAAg=,iv:QGV4eSuBl3rhcdwz3iyYPA3SQFGYvXxoaHvRvJxoKDY=,tag:SB00tN7Qlp0KsDHg72Y2gw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
