apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_CLUSTER_NAME: ENC[AES256_GCM,data:3i/FUVaesvE=,iv:1q3r8FC/oeCX46hi9ROyrGVhUkwk81c1tQZQHmVXd+k=,tag:ctkNp30RUQmh+HG2w169iQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:0r9nF8Y=,iv:pTfIeRsxhWcJczBoWaLud8gIfxhlNZ/S7pfUBjct99M=,tag:pcjJXMulP5A3p/TOJK6lxQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:ocMoiAA04XI=,iv:Oqn7NoiaEzjwkRiWrFTptYxMIty2a6ZEi+nf7YordYE=,tag:QDqmOHhV2ZPOlG4+icRi4g==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:mX8r6K+3U7TU5bAw9HccDff6dibFaYfRePLab+mKcqLtRB8k,iv:wJUyMBIzv8qCAcRxWPFL8sEwuuaz9UKTHB/C216Zn2I=,tag:xlGVwhit/wgEwz3Dl+jWcg==,type:str]
    STORAGE_CLUSTER_NAME: ENC[AES256_GCM,data:PSlFEgWvDgI2Cqfi,iv:w/TSBCoCocD+2WW0ybF/flEUTRfUXmZkejMypyqneTU=,tag:11CTZQFUjyjvG6dVkvssRw==,type:str]
    STORAGE_DOMAIN: ENC[AES256_GCM,data:sw+IcVyKUsZrLTwgVw==,iv:F3v1nWcC9X/IO9rB7VS9WgUwELpc6KCJE3uj1P434m4=,tag:ruCH0jht+Vspl8es5opUtg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ve9kzacrwq7l9l0emvs326uk6t576d75r596e083r2tq6xu28qcsacy3s7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRDE0Uk5KaW5uRkNHaGpv
            VkgyV0N2RDNZS2Q4bXd2TVMxZWw4VStRc1hrCm5hNnA0ZEZTV2QyeEx1Zm5IbmZy
            am9TTk92V2RMWnlHcFZpZVcyb3FQRDQKLS0tIFQ3aVBhajVlZDJSWEtCcXhzc2Q3
            ME5zYlpMbVk3NHljVEdJNk1ocG91c28KNfYzJ15YFgpNvmM4mWC7FD4jTu/IwnHx
            SWN3WbZK2qc4oTrNBKTA8DQ+7MF4VbbBmq7FXVNYGVns9xDrgVO9DQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-21T21:43:14Z"
    mac: ENC[AES256_GCM,data:Lz81Aedj5vE4YMGs0vPTGpV8pzS06OZpqgQMfdMRj1XPaHYVjRaTPIxGFXFZnWDYBQp+seq7deGkU4T1cHroP0/tx5NItlGWJot/Offv9DnVkjfy8mzEm27a5m9JGDTRihHOAtra92Fy+K63FXZIdeBsUlLORojhkDIykZS9C5k=,iv:3SBagIm4UXhMnA5cFb6AtPP/RtIBrd2K01JM0dX2Eg0=,tag:H2f3XzBo2sgOgfafVftQCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
