apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-config-secret
stringData:
    logger: ENC[AES256_GCM,data:Y8XkLaY=,iv:/W1XgLRSrRbODnL3PePS3EmP2cC88y8MvH33219PE+Q=,tag:YvDdQDSvd1NofYYFSBmy9A==,type:str]
    #ENC[AES256_GCM,data:PB7+s+spHskovf27/RYu,iv:80t8irIlgACM9ETstPg3xCbZMY0IZXjfSjM51ka0Bxc=,tag:gzMj8hS9bUFD1Ppb2Z7/Hg==,type:comment]
    internal_url: ENC[AES256_GCM,data:6XAYKGQEXGKFuuPc36dbeDJqvfv9EPy5kQYD,iv:e9A2nT5W04Ujps73u5F9kBC8u11aCphg0757fKtJstM=,tag:fDlRr+4HbEZsgX9q58PSQA==,type:str]
    internal_url_direct: ENC[AES256_GCM,data:ZwSTNBGYIT0++kuFDfCnd/KgLb4a+RhNdg+y,iv:bDmQG+pJIIpHljkNW5eCkUMx3cx6uxT7OONJscPCWEo=,tag:PFWPl3Be4jpGEtBHuZa7jw==,type:str]
    trusted_proxy_1: ENC[AES256_GCM,data:OKDWlcL+rOqM6Uxh,iv:Udrg1J0PKaaJpwBFzj2vv1479Z/hxsrkJX6UHMLItf4=,tag:3LTK+glHoyfYo/UNmmKvng==,type:str]
    #ENC[AES256_GCM,data:M3iLmtqMGj8Nsa3aIpq0l9VfsRog,iv:5Z7yQFCzJ0TkGSebou5cu/qEWxcvw/gp7Wg0wFiArJI=,tag:GrCmh/j0W+afWAH7UoIvVg==,type:comment]
    zone_home_name: ENC[AES256_GCM,data:TgnLbjj6Oeg=,iv:S0JPNuADf6wxi0bXcO0/J6xV7capXEla5ZDPRyFUMtw=,tag:CyWV2ktHL9TYDFzEG2K2gw==,type:str]
    zone_home_latitude: ENC[AES256_GCM,data:SM+93ArHPaHBSNM=,iv:cO+3ufO6dGfTkX6iP3fBTBrttaf7PZ9mDlUpvl4fchU=,tag:5ugGFYaILzgsX/GRxH6jwA==,type:str]
    zone_home_longitude: ENC[AES256_GCM,data:fIoGxQ07y7g15CA=,iv:CQYDO3CK8z5bqsZ8o+ftmW9hlbqXanYu0am1cN10yfU=,tag:oPDLLm1gVQ9ypFixWpLPkg==,type:str]
    zone_home_elevation: ENC[AES256_GCM,data:jiNZ,iv:J3TV0SyqEEOJOsLEYqL5z6JYyKxKM6IalfMum5B6HRQ=,tag:IzuSl5W7QT6n19geWd733w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ve9kzacrwq7l9l0emvs326uk6t576d75r596e083r2tq6xu28qcsacy3s7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcEpDL2k1dzN5UmVuN29T
            SFY4VzlRYktXWGFiMFcxK2x6aVpuQWtRL1ZBCkNlZzYxcmtPYkJUWlVPbXFmeXlE
            cTBFTllZbWNNWDRXQVVncTlPTlNFWk0KLS0tIGgrR2UvNDFUVmNkT0l1K1ZxeXJh
            OFIvbmJyN3ZCTVRvQ2RmMG5aTisrMWsKdCFaqnIIqsrDOnq2u6fPkcK4Mv3MIbd/
            T3txCFmZZRa7Hdi0bHHCWdKvAPe49/+ornrl72O+YFvdTn50sBKbRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-29T17:25:45Z"
    mac: ENC[AES256_GCM,data:JUsRnhX6h3wruqEdQkOhCCBiWHi2vl7KX06TFU33tj8P6gjjp3NF0yJYKRAVd2z5VLB+xpfFIRjLYFemEwaibEWEZLm6bA/4rsEijzFfblNzFfn28ZI7ej+Cjy+NKakLw+tZBtspDhma5NCM+nr1ZpzF1KGuan9HteH81UJ9hhk=,iv:/ROTSfAPJN9WeCM89PfaeA+6tOLz9iujxXoTrm0ineQ=,tag:6zHsvkUBcfyDea2tBaVdUw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
