apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-config-secret
stringData:
    #ENC[AES256_GCM,data:PB7+s+spHskovf27/RYu,iv:80t8irIlgACM9ETstPg3xCbZMY0IZXjfSjM51ka0Bxc=,tag:gzMj8hS9bUFD1Ppb2Z7/Hg==,type:comment]
    system_logger: ENC[AES256_GCM,data:RM40u3U=,iv:O2Z0zZCx0dF10Aroq/rxBlQTHCP4DML+yKtTFpSoeSU=,tag:DYzYd6uz8F3XXB9tJPl5jQ==,type:str]
    system_url_external: ENC[AES256_GCM,data:lySjJt5HRLazLjfw4vNQqGiQ,iv:eh+3iAAA5CZzTpxoZWUf9eec+vIEzmqBcdrhwhI1vq0=,tag:9l1Wfyez1KfF9u3VzK/uaA==,type:str]
    system_url_internal: ENC[AES256_GCM,data:YaMqB774XLfGlZJQQLPk9Syb94UL7N3GWjaO,iv:MhsWUU/wfO4Ko5ia779SfOthiv8MJC2C3u0M8NdgwqY=,tag:Fn1Gh7lQe67s3R40PT0Vog==,type:str]
    system_url_service: ENC[AES256_GCM,data:gXcGbtTSGevcaNrjWOu9aJsm2zlctLc5wxUj4+nhovpxXzvI33y8ScyF/mPNa+gFVGnT5UziUMCRJqDk,iv:f4MsmMbAaoIgdQ5e6c2tfYUphAL6B+sw3jhvx9L9tqY=,tag:z0IhEcCnuLSOYEPMPiDZnw==,type:str]
    trusted_proxy_1: ENC[AES256_GCM,data:OKDWlcL+rOqM6Uxh,iv:Udrg1J0PKaaJpwBFzj2vv1479Z/hxsrkJX6UHMLItf4=,tag:3LTK+glHoyfYo/UNmmKvng==,type:str]
    #ENC[AES256_GCM,data:M3iLmtqMGj8Nsa3aIpq0l9VfsRog,iv:5Z7yQFCzJ0TkGSebou5cu/qEWxcvw/gp7Wg0wFiArJI=,tag:GrCmh/j0W+afWAH7UoIvVg==,type:comment]
    zone_home_latitude: ENC[AES256_GCM,data:hMSfvUQhiwAw4w==,iv:4BHabajf5H5CcGWRJ77GylchI9oDUnZzapd42hg2YU8=,tag:MGkFKVRbbOqbSoKWwgh1lg==,type:str]
    zone_home_longitude: ENC[AES256_GCM,data:uy0vGDaXmM4wrQ==,iv:TQtlLVh0jBWv/gAFQpMSEFLaZ3l1gYJaDSuZVuTAR+0=,tag:tYkR63ec5lh0msRICg//iQ==,type:str]
    zone_home_elevation: ENC[AES256_GCM,data:jiNZ,iv:J3TV0SyqEEOJOsLEYqL5z6JYyKxKM6IalfMum5B6HRQ=,tag:IzuSl5W7QT6n19geWd733w==,type:str]
    #ENC[AES256_GCM,data:44V/QYBqbP7EW7hwSNhoj1yCgex/jkMCBax4sQ==,iv:STkd1G7S6UgKp8GgxRbfEDrvBcuaRAeyJKuTfAax9pU=,tag:MqzD4SWzpDUkwodcrCsIAw==,type:comment]
    zone_home_radius: ENC[AES256_GCM,data:0Qk=,iv:1TAZkYsh78vfDXE2l+f70/2K7yhVWWIpSNzd+LkxDdU=,tag:FzXpLob7ivuXmsmxIUTqaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ve9kzacrwq7l9l0emvs326uk6t576d75r596e083r2tq6xu28qcsacy3s7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcEpDL2k1dzN5UmVuN29T
            SFY4VzlRYktXWGFiMFcxK2x6aVpuQWtRL1ZBCkNlZzYxcmtPYkJUWlVPbXFmeXlE
            cTBFTllZbWNNWDRXQVVncTlPTlNFWk0KLS0tIGgrR2UvNDFUVmNkT0l1K1ZxeXJh
            OFIvbmJyN3ZCTVRvQ2RmMG5aTisrMWsKdCFaqnIIqsrDOnq2u6fPkcK4Mv3MIbd/
            T3txCFmZZRa7Hdi0bHHCWdKvAPe49/+ornrl72O+YFvdTn50sBKbRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-09T17:20:20Z"
    mac: ENC[AES256_GCM,data:TxzG55QMVMCJe8hh9RVSdFRPE+jIPT1avYxIMuQEMXaHjRZvgOvw5jb3hrdVCfD3nfzU2N8GdTGFQziUAvQAm234dz2MMrhyzLaEyYpRIOOVmMpbVfVXbInl/ZTeL5Et9m16oKml0P6ZEP8l8h7GH+CooWSamqIZQ2YFywlZ/as=,iv:vbNTDp1mGFxFscNNV5DtjY9QUiRpQp1y7vFC3EW6ahU=,tag:tbJ65mSUoBq1xIhEM1kBRg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
