---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant-emqx-init
spec:
  target:
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        INIT_EMQX_API_HOST: "{{ .emqx_api_host }}"
        INIT_EMQX_API_PORT: "{{ .emqx_api_port }}"
        INIT_EMQX_ACCESS_KEY: "{{ .emqx_username }}"
        INIT_EMQX_SECRET_KEY: "{{ .emqx_password }}"
        INIT_EMQX_USER: "{{ .hass_username }}"
        INIT_EMQX_PASS: "{{ .hass_password }}"
        INIT_EMQX_TOPIC: "homeassistant/#"
        # https://github.com/home-assistant/core/blob/dev/homeassistant/generated/mqtt.py
        INIT_EMQX_TOPIC_ACLS: >-
          {{ .hass_username }}:drop_connect/discovery/#:all:allow
          {{ .hass_username }}:dsmr/#:all:allow
          {{ .hass_username }}:esphome/discover/#:all:allow
          {{ .hass_username }}:fully/deviceInfo/+:all:allow
          {{ .hass_username }}:tasmota/discovery/#:all:allow
  dataFrom:
    - extract:
        key: emqx-secret
      rewrite:
        - regexp:
            source: "^(.*)$"
            target: "emqx_$1"
      sourceRef:
        storeRef:
          name: emqx-secret-store
          kind: ClusterSecretStore
    - extract:
        key: home-assistant-emqx-secret
      rewrite:
        - regexp:
            source: "^(.*)$"
            target: "hass_$1"
      sourceRef:
        storeRef:
          name: home-automation-secret-store
          kind: SecretStore
