---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: postgres-operator
      namespace: database
    - name: emqx-operator
      namespace: database
    - name: external-secrets
      namespace: security
    - name: multus
      namespace: kube-system
    - name: volsync
      namespace: storage
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: nabucasa.feature.node.kubernetes.io/skyconnect
                    operator: Exists
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [{
            "name":"multus-iot",
            "namespace": "kube-system",
            "ips": ["192.168.101.254/24"]
          }]
        secret.reloader.stakater.com/reload: "home-assistant-emqx-init,home-assistant-secret"
      securityContext:
        runAsUser: 0
        runAsGroup: 0
    controllers:
      home-assistant:
        containers:
          app:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2024.7.4
            envFrom:
              - secretRef:
                  name: home-assistant-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /manifest.json
                    port: 8123
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup: *probes
            resources:
              requests:
                cpu: 100m
                memory: 2Gi
              limits:
                memory: 2Gi
          code-server:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.91.1
            args: [
              "--auth", "none",
              "--user-data-dir", "/config/.vscode",
              "--extensions-dir", "/config/.vscode",
              "--port", "80",
              "/config"
            ]
            resources:
              requests:
                cpu: 10m
                memory: 2Gi
              limits:
                memory: 2Gi
            lifecycle:
              postStart:
                exec:
                  command:
                    - /bin/sh
                    - -c
                    - |
                        (
                          set -ex
                          apt update
                          apt install --yes dnsutils
                          apt install --yes iproute2
                          apt install --yes inetutils-ping
                          apt install --yes inetutils-telnet
                          apt install --yes inetutils-traceroute
                          apt install --yes net-tools
                        ) > /tmp/postStart.log 2>&1 || true
        initContainers:
          emqx-init:
            image:
              repository: ghcr.io/prehor/emqx-init
              tag: 1.0.0
            envFrom:
              - secretRef:
                  name: home-assistant-emqx-init
          recorder-initdb:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom:
              - secretRef:
                  name: home-assistant-postgres-recorder-initdb
          config:
            image:
              repository: docker.io/alpine/git
              tag: 2.45.2
            command: ["/bin/sh","-c"]
            args: |
              set -ex
              if [ ! -e "/config/.git" ]; then
                git clone git@github.com:prehor/hass-config.git /config/.hass-config
                mv /config/.hass-config/* /config/.hass-config/.* /config
                rmdir /config/.hass-config/
              fi
          usbip-attach:
            image:
              repository: ghcr.io/prehor/usbip
              tag: 6.6.31
            restartPolicy: Always  # Sidecar container
            env:
              USBIP_HOST: h1.${SECRET_DOMAIN}
            lifecycle:
              preStop:
                exec:
                  command:
                    - /entrypoint.sh --detach
            securityContext:
              privileged: true
    service:
      app:
        controller: home-assistant
        ports:
          http:
            port: 8123
          code-server:
            port: 80
    ingress:
      app:
        enabled: true
        className: internal
        hosts:
          - host: &host hass.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
      code-server:
        className: internal
        hosts:
          - host: &host "hash.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: code-server
        tls:
          - hosts:
              - *host
    persistence:
      config:
        existingClaim: *app
      deploy-key:
        type: secret
        name: home-assistant-config-deploy-key
        defaultMode: 0o400
        globalMounts:
          - path: /root/.ssh/id_ed25519
            subPath: ssh-privatekey
          - path: /root/.ssh/known_hosts2
            subPath: ssh-known-hosts
      host-dev:
        type: hostPath
        hostPath: /dev
        globalMounts:
          - path: /dev
            mountPropagation: HostToContainer
      host-sys:
        type: hostPath
        hostPath: /sys
        advancedMounts:
          home-assistant:
            usbip-attach:
              - path: /sys
                mountPropagation: Bidirectional
      logs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
      tts:
        type: emptyDir
        globalMounts:
          - path: /config/tts
      tmp:
        type: emptyDir
