---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-postgres-dburl
spec:
  target:
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        recorder_db_url: "postgresql://{{ .postgres_recorder_username }}:{{ .postgres_recorder_password }}@{{ .postgres_host }}:{{ .postgres_port }}/{{ .postgres_recorder_database }}"
  dataFrom:
    - extract:
        key: postgres-secret
      rewrite:
        - regexp:
            source: "^(.*)$"
            target: "postgres_$1"
      sourceRef:
        storeRef:
          name: postgres-secret-store
          kind: ClusterSecretStore
    - extract:
        key: home-assistant-postgres-recorder-secret
      rewrite:
        - regexp:
            source: "^(.*)$"
            target: "postgres_recorder_$1"
      sourceRef:
        storeRef:
          name: home-automation-secret-store
          kind: SecretStore
