---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant-postgres-recorder-initdb
spec:
  target:
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_HOST: "{{ .postgres_host }}"
        INIT_POSTGRES_PORT: "{{ .postgres_port }}"
        INIT_POSTGRES_SUPER_USER: "{{ .postgres_username }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .postgres_password }}"
        INIT_POSTGRES_DBNAME: "{{ .postgres_recorder_database }}"
        INIT_POSTGRES_USER: "{{ .postgres_recorder_username }}"
        INIT_POSTGRES_PASS: "{{ .postgres_recorder_password }}"
  dataFrom:
    - extract:
        key: postgres-secret
      rewrite:
        - regexp:
            source: "^(.*)$"
            target: "postgres_$1"
      sourceRef:
        storeRef:
          name: postgres-secret-store
          kind: ClusterSecretStore
    - extract:
        key: home-assistant-postgres-recorder-secret
      rewrite:
        - regexp:
            source: "^(.*)$"
            target: "postgres_recorder_$1"
      sourceRef:
        storeRef:
          name: home-automation-secret-store
          kind: SecretStore
