---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-secret
spec:
  dataFrom:
    - extract:
        key: home-assistant-config-secret
      rewrite:
        - regexp:
            source: "^(.*)$"
            target: "hass_$1"
      sourceRef:
        storeRef:
          name: home-automation-secret-store
          kind: SecretStore
    # - extract:
    #     key: home-assistant-postgres-dburl
    #   rewrite:
    #     - regexp:
    #         source: "^(.*)$"
    #         target: "postgres_$1"
    #   sourceRef:
    #     storeRef:
    #       name: home-automation-secret-store
    #       kind: SecretStore
