---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: postgres-secret-store
spec:
  provider:
    kubernetes:
      remoteNamespace: database
      auth:
        serviceAccount:
          name: postgres-secret-manager
          namespace: database
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: database
          key: ca.crt
