---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-secret-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgres-secret-manager-role
rules:
  - apiGroups: [""]
    resources:
      - secrets
    resourceNames:
      - postgres-secret
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - authorization.k8s.io
    resources:
      - selfsubjectrulesreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-secret-manager-binding
subjects:
  - kind: ServiceAccount
    name: postgres-secret-manager
    namespace: database
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: postgres-secret-manager-role
