apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:NdHF9Qwkz2IchN7ZNAkOc8T79g==,iv:poEpMBBUdLZ74/tXT7Pl0YEpA77ipzXQbCuCv2BxQfc=,tag:M7GGoQ9plf7pB9M+CJoWAQ==,type:str]
    password: ENC[AES256_GCM,data:NelCvK8JWiVYs/SKznJdL22BxeqOJigxfTH5/dOD0Ygp1DXdVn7Dng==,iv:XcgLYqPq0bczrBtJ0bRyzm8die/AnHPJda4UI0bWpYw=,tag:V9wSU1SgCeJGK/QBCQrWWQ==,type:str]
    host: ENC[AES256_GCM,data:pEoSsfmguoxU8+5UdJ0zpW3qwI7kfQGfCMLJYUmr/TqpqfKmjMs6Qw==,iv:fZQxWS0tHCj7Tv4zBAO484/ArrlavPMD+DMfHY7Zrbk=,tag:Tcn+sWX7u09RAoMyN09sUw==,type:str]
    port: ENC[AES256_GCM,data:0lFLtQ==,iv:FEISHo/SmZFewMPgf1tYTVVv9Mx+rBogi/z3bzhHu5M=,tag:8eiii2SP4l7D3cqvA+CvNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ve9kzacrwq7l9l0emvs326uk6t576d75r596e083r2tq6xu28qcsacy3s7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJejJZUUVQYmtwZ2l6MEcr
            U0k4ajRWUnVjdmc2U3VQQWZYUitDTU9vTlVFCm9uWE9URWFmS05TK0Irdm1zMHNj
            MFcwR0FKM0Y0RmxmYTlIWlhDL3ZrTnMKLS0tIEFhdzIzemlDaHlORzhueWpCcDR6
            TFVsdVdLWTNvV3BVaGN0b0lFeFBCcVkKHk5dzlxehWoltG2KKfggnoISjpLi1UY9
            KOWf7mbkJihA3Et9aP5MJqxs+hDqBG6awMdrrso/YxFrrYygAHpQbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-28T21:46:00Z"
    mac: ENC[AES256_GCM,data:dfxOb4Yy/z0vrwidknhympJL2MwWN92TBUAke2aWjrwKyRUnsI7Hp9S2Isf+vwaWCTIZeEA5ziN3Giaes8vnn7U7WjQGcno7ZLwSZtDnz48E6TYn/9wrAPUYyPmcsgpmQn9CKXF4irpipbsszWsWFawG8BIPyfajpLNqfVNz+lA=,iv:mcCuERx9mYGLN0C5UkpBxx8IRy8QqYY89+/acVUSeEE=,tag:ezCVaqjiPV++/q4c7wQZxg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
