---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: storage-secrets-manager
rules:
  - apiGroups: [""]
    resources:
      - secrets
    resourceNames:
      - minio-secret
      - volsync-secret
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - authorization.k8s.io
    resources:
      - selfsubjectrulesreviews
    verbs:
      - create
