---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./snapshot-controller/ks.yaml
  - ./minio/ks.yaml
  - ./openebs/ks.yaml
  - ./rook-ceph/ks.yaml
