---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./backube.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./cluster-proportional-autoscaler.yaml
  - ./descheduler.yaml
  - ./emqx.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./ingress-nginx.yaml
  - ./k8s-gateway.yaml
  - ./k8tz.yaml
  - ./jetstack.yaml
  - ./metrics-server.yaml
  - ./node-feature-discovery.yaml
  - ./openebs-zfs-localpv.yaml
  - ./openebs.yaml
  - ./rook-ceph.yaml
  - ./piraeus.yaml
  - ./stakater.yaml
