---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  - ./descheduler/ks.yaml
  - ./k8tz/ks.yaml
  - ./kube-vip/ks.yaml
  - ./metrics-server/ks.yaml
  - ./multus/ks.yaml
  - ./node-feature-discovery/ks.yaml
  - ./reloader/ks.yaml
