---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: home-automation-secret-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: home-automation-secret-manager-role
rules:
  - apiGroups: [""]
    resources:
      - secrets
    resourceNames:
      - ebusd-config-secret
      - home-assistant-config-secret
      - home-assistant-emqx-secret
      - home-assistant-postgres-dburl
      - home-assistant-postgres-recorder-secret
      - zigbee2mqtt-config-secret
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - authorization.k8s.io
    resources:
      - selfsubjectrulesreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: home-automation-secret-manager-binding
subjects:
  - kind: ServiceAccount
    name: home-automation-secret-manager
    namespace: home-automation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: home-automation-secret-manager-role
