---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/secretstore_v1.json
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: home-automation-secret-store
spec:
  provider:
    kubernetes:
      remoteNamespace: home-automation
      auth:
        serviceAccount:
          name: home-automation-secret-manager
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
