---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app coredns-config
  namespace: flux-system
spec:
  targetNamespace: kube-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/main/apps/kube-system/coredns/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
