---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
spec:
  interval: 30m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.16.0
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    master:
      resources:
        requests:
          memory: 32Mi
        limits:
          memory: 64Mi
    worker:
      config:
        core:
          sources: ["pci", "system", "usb"]
      resources:
        limits:
          memory: 64Mi
    prometheus:
      enable: true
