---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./home-storage-echo-server.yaml
  - ./home-storage-flux-webhook.yaml
