---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
data:
  custom.override: ""
  custom.server: |
    storage.rx.cz:53 {
        errors
        cache 30
        forward . 192.168.1.19
    }
