apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:jRVr/qMuSIXXQxyiDp4wqhfoBMw2ewBrDz7jI+bFoA97jDnz,iv:386NkYKEot+UlZzbbfM+m43E+F0Ipd6Vw4UngZCiDiU=,tag:wvZTOxeTDsH4vddRco+3vQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:aj8itbbX+0YjdanlzRPbv5hyHmcTJdY8jcPGiX50QULsagQ/6uELmct+ZyVMQHJ4Gn1/y2rLUL2WXDVDlOyfQLcL86EMRX9WBxOn00HNObSMtyIZTMc6Na9vO0pMavJ5hM35xKXUjWSQxIvsQr/dLWoghrB5jTCyHtjSuLOPxCFxyvCMd/4wCz+Ez0XsEaHmde5/U4KhSFntNkgcwOErEuiZhPf0SHP0EEfygjcmaA==,iv:mEp+JOnf/F1X2ej4R5vttoren7gPlB8kSIzXpJSxt/k=,tag:+oqyTbay/powKur1fM6vIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ve9kzacrwq7l9l0emvs326uk6t576d75r596e083r2tq6xu28qcsacy3s7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOEtad2RxV2N1WkV3SUFT
            VXo3RjB3ekNsNFcxMUM5L2FSVktMNjh3TEdrCmVKcU04dFVUWnNWYTBKRi90cUZz
            WVJGNXJaVG1pQ1pKY2hsZlUzZ0l4bFUKLS0tIHAyYlhEUjNvcFhYaEpYdVBpTmZK
            UllMOUNyOHVsMUM3ZDN0YjJQUjNhQVkKTo7l1+wXeqdmkYnPp/5vKjSh5VsuDxBY
            DftjoAmkB/MdRM1OuIRaopMvkU8UCTxWRmtJ5tm44ljc7B75/GYWDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-21T17:52:58Z"
    mac: ENC[AES256_GCM,data:ht0DxRaQbOXFm7CCaYKtzPK4q6HPh++aNkt8/85ujair9WKR0S0DKUbyaqanE5xEfw0QE1emnrhq1JW8fnd2vce6PAFgfUOg7nNeesAoFFHDHLGwt1EYZa1gZOgUSxrYl88ePoaJ6FhFNHi4U8xF81FEbOZ0nwQEpu4dRQE8L9I=,iv:PaiBn29vE68wUa7OfwL3YAxf/rRPSTT1+AlnWDFfVZc=,tag:pNWYyg9e98BvdDhe4/8Z2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
