---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8tz
spec:
  chart:
    spec:
      chart: k8tz
      version: 0.18.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: k8tz
        namespace: flux-system
  interval: 30m
  values:
    namespace: kube-system

    replicaCount: 1

    timezone: Europe/Prague
    cronJobTimeZone: true

    webhook:
      certManager:
        enabled: true
        issuerRef:
          kind: ClusterIssuer
          name: selfsigned

  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Namespace
            patch: |-
              $patch: delete
              apiVersion: v1
              kind: Namespace
              metadata:
                name: not-used
