---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: k8tz-webhook-selfsign
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8tz-webhook-ca
spec:
  secretName: k8tz-webhook-ca
  duration: 43800h # 5y
  issuerRef:
    name: k8tz-webhook-selfsign
    kind: Issuer
  commonName: "ca.k8tz.cert-manager"
  isCA: true
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: k8tz-webhook-ca
spec:
  ca:
    secretName: k8tz-webhook-ca
