apiVersion: v1
kind: Secret
metadata:
    name: volsync-secret
stringData:
    BACKBLAZE_ACCESS_KEY: ENC[AES256_GCM,data:BYVsKQRGLPzQNXmKuFqE/zxpDodXqklnNw==,iv:IQqQprf8SU4tVl3itLHVF5RzIdEyOagy7k4PhzH1EBk=,tag:N/uMXGppD3nNhkioLGemLQ==,type:str]
    BACKBLAZE_SECRET_KEY: ENC[AES256_GCM,data:ggPtXu2J2WAA0cEsFOadauKVMZf72qiW9KRwzOVsrg==,iv:omm4AvVPsSiX0ZgSwuwVHkLZ7vfkhlJFbZNv5ir8kBM=,tag:JILjUcJ4HELIg1xwq34M3Q==,type:str]
    BACKBLAZE_REPOSITORY: ENC[AES256_GCM,data:U+RYL4dMwkHhQE5Iu41SrRbxkjFu3FYfEteAz4ZqPjn7D44a4FmSXEYb6xddWRQrHIStx4BOHsWyUcc8htlupOT4yg==,iv:1zG7sPXpUeT+m1nfC2q1U/k1pv2JTP2mXfTqLlqGUxg=,tag:jFsrVMGpGc+0hGXr7R1N4A==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:HuvbaVh8m5Qb/hy1Sl5aYAtquP0=,iv:KBU1aP8duts53ylM9VRrtunQesblHHO/NPY+bh4asDU=,tag:cRSG3uiIoDRb34+0Q6hRJg==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:tvB7rgl/lFOSt7q6gOCEWRCzZlyCTqz15DlyRRUQtFwcBJfILPF+eA==,iv:1U+2zV21DVEZxBz9B/n0GjxVVUPY1fuwHpVtIea3Xvo=,tag:GdVRxmbpoTwhF1dcFHPKqw==,type:str]
    MINIO_REPOSITORY: ENC[AES256_GCM,data:7P7iUH06dmH8tGDfdiH0Fa2VI+6ZRcH24chSiz9nM2u+fxcm1qT3ENgnxtcK/nn4H8A09Y/o,iv:zBu6Kj7H/JH/72L7nSYUwF6xv8uVb05QoU/XyemLGEg=,tag:7rdQq0Zv0Bt0DP+jjmmjjA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:OutPX3ZJDNcW4ZnSxeUj/47RBKf1bbkge/52H3xfTy3XO7n4BObuEHOqfEjITnxt0dpDM588a0bTclmB8MoDJQ==,iv:8RSryIOUNsLj6c9JlAYPyWSia87ojwqe12/CRUxXlas=,tag:YoidVddlHlXl4q7MOP9Ljw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ve9kzacrwq7l9l0emvs326uk6t576d75r596e083r2tq6xu28qcsacy3s7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVK1FDUE5ydDM2SzA0ZWFr
            ZElOb1JXUjA3Z0NIYW1wZnJvZjdXNC8zV0Y0CjRKbHpvVmtKRVIvRmF4V1dGY3ly
            SWpuc0RhcEdqcHpKcTZiNko5VG1LS2cKLS0tIFVvOERtQVF4ZFVTMk1MZ3A1QnFT
            RFN6U2lQU2Q3M0wwYmNuc0pLN1IzczQKwRAph52iWkz4M/qYBepyfe0OKZV9Qyje
            LglPEeuTwBc+sybPVtiXIcFzPfIcI03yPsvdFbTbn5eRJWBOA7t3JQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-12T18:47:06Z"
    mac: ENC[AES256_GCM,data:D39SZqxPKAdi+2nPeDiC7/hdugYxTOMsB1ZnQ0Ezce2T6IhmylsOfzmrj+wRo7JJkNp4uOV6dPpFBOuntQuGVducByCrtMjLbNs+Y60dEODxSVGGziUUtLmrvjmvuv8jKYnIrHsHUvt0ZOQbjXBpX279jSi49La7mAXMOliRssQ=,iv:Ap918qkqmUAVotWCdnzqfStI6aRQfEBjK5g8QvGxNR8=,tag:U7V5up7tv+rWbUY5TiiA0g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
