---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app coredns-autoscaler
spec:
  interval: 30m
  chart:
    spec:
      chart: cluster-proportional-autoscaler
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: cluster-proportional-autoscaler
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: *app
    config:
      linear:
        coresPerReplica: 4
        nodesPerReplica: 1
        preventSinglePointFailure: true
        includeUnschedulableNodes: true
    options:
      logLevel: 4
      pollPeriodSeconds: 300 # 5 min
      namespace: kube-system
      target: deployment/coredns
    resources:
      requests:
        cpu: 10m
        memory: 256Mi
      limits:
        memory: 256Mi
    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 568
      runAsGroup: 568
    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
