---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Prevent Merging"

on:
  pull_request:
    types: [synchronize, opened, reopened, labeled, unlabeled]

jobs:
  prevent-merging:
    name: Prevent Merging
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@8afbe8ae6ab7647d0c9f0cfa7c2f939650d22509 # v5.5.1
        with:
          count: 0
          mode: exactly
          labels: ^hold/
          use_regex: true
